# Generated by Django 5.1.4 on 2024-12-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('disponible', models.BooleanField(default=True)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
            },
        ),
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('historial', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClasesPedido.historial')),
                ('mesa', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClasesPedido.mesa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observacion', models.TextField(blank=True, default='Ninguna')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido_list', to='ClasesPedido.cliente')),
                ('plato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClasesPedido.plato')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Items del Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateTimeField(auto_now=True)),
                ('informacion', models.TextField(editable=False)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('estado', models.CharField(choices=[('EN_PREPARACION', 'en_preparacion'), ('PAGADO', 'pagado'), ('PENDIENTE', 'pendiente'), ('PREPARADO', 'preparado'), ('SERVIDO', 'servido'), ('RESERVADO', 'reservado')], max_length=50, null=True)),
                ('item_pedido_list', models.ManyToManyField(to='ClasesPedido.itempedido')),
                ('mesa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClasesPedido.mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('identificacion', models.CharField(editable=False, max_length=7, unique=True)),
                ('esta_ocupado', models.BooleanField(default=False, editable=False)),
                ('pedidos', models.ManyToManyField(blank=True, editable=False, to='ClasesPedido.pedido')),
            ],
            options={
                'verbose_name': 'Mesero',
                'verbose_name_plural': 'Meseros',
            },
        ),
        migrations.AddField(
            model_name='historial',
            name='pedidos',
            field=models.ManyToManyField(to='ClasesPedido.pedido'),
        ),
        migrations.CreateModel(
            name='PersonalCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('identificacion', models.CharField(editable=False, max_length=7, unique=True)),
                ('esta_Cocinando', models.BooleanField(default=False, editable=False)),
                ('pedidos', models.ManyToManyField(blank=True, editable=False, to='ClasesPedido.pedido')),
            ],
            options={
                'verbose_name': 'Personal de Cocina',
                'verbose_name_plural': 'Personales de Cocina',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platos', models.ManyToManyField(to='ClasesPedido.plato')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clientes', models.ManyToManyField(blank=True, to='ClasesPedido.cliente')),
                ('menu', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ClasesPedido.menu')),
                ('mesas', models.ManyToManyField(blank=True, to='ClasesPedido.mesa')),
                ('meseros', models.ManyToManyField(blank=True, to='ClasesPedido.mesero')),
                ('pedidos', models.ManyToManyField(blank=True, to='ClasesPedido.pedido')),
                ('personal_cocina_list', models.ManyToManyField(blank=True, to='ClasesPedido.personalcocina')),
                ('registro_historico', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='restaurante', to='ClasesPedido.registrohistorico')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
    ]
