# Generated by Django 5.1.4 on 2024-12-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClasesPedido', '0002_alter_restaurante_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='registro_historico',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurante', to='ClasesPedido.registrohistorico'),
        ),
    ]
