# Generated by Django 5.1.4 on 2024-12-23 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClasesPedido', '0004_remove_pedido_item_pedido_list_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalcocina',
            old_name='esta_Cocinando',
            new_name='esta_cocinando',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='observacion',
            field=models.CharField(blank=True, default='Ninguna', max_length=100),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido_list', to='ClasesPedido.pedido'),
        ),
    ]
